### ISSUE TITLE
When taping multiple times on nodes

### ISSUE THREAD

**Issue by satyanandt** [andersonlucasg3/SpriteKit-Android#7]
E/AndroidRuntime: FATAL EXCEPTION: GLThread 5789
    java.lang.IllegalStateException: it must not be null
        at br.com.insanitech.spritekit.engine.SKActionEngine.updateChildrenActions(SKActionEngine.kt:25)
        at br.com.insanitech.spritekit.engine.SKActionEngine.evaluateActions(SKActionEngine.kt:14)
        at br.com.insanitech.spritekit.engine.SKEngine.doUpdateFlow(SKEngine.kt:52)
        at br.com.insanitech.spritekit.engine.SKEngine.drawFrame(SKEngine.kt:69)
        at br.com.insanitech.spritekit.opengl.renderer.GLRenderer.onDrawFrame(GLRenderer.kt:39)
        at br.com.insanitech.spritekit.opengl.renderer.GLGenericRenderer.onDrawFrame(GLGenericRenderer.kt:24)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

**Comment by andersonlucasg3** [comment]
Thanks for the report.
Gonna have a look into it.
Feel free to fork and create a pull request as well.
